### ISSUE TITLE
join the team

### ISSUE THREAD

**Issue by kanishka-work** [OCamlverse/ocamlverse.github.io#108]
Leave this open for people who want to join?

**Comment by kanishka-work** [comment]
Please add me as maintainer. Thanks!

**Comment by bluddy** [comment]
Hey @kanishka-work, thanks for asking to join. Since making changes with a PR is easy, I'd like to see some contributions first, if possible, before adding people to the team.

Initially, the site was empty, and I was encouraging anyone to join, but now it's a resource that's used quite heavily by the community, so becoming a maintainer is going to require some PR history. Sorry about the misleading info in the opening page. I'll make sure to change that.

**Comment by kanishka-work** [comment]
will contrib, but no need to add me as maintainer, just following the documented notes,

**Comment by bluddy** [comment]
Thanks for being so understanding. I'd love to have a bigger team maintaining the site, but I really need to make sure I'm only adding people who will readily contribute and maintain the structure of the site. The guidelines I wrote way back when ocamlverse started are not as relevant today, and I hadn't gotten back to fixing them.
